import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./pages/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="sticky top-0">
        <Navbar />
        </div>
        <div className="content-wrapper">
          {children}
        </div>
      </body>
    </html>
  );
}
